#Minecraft Fabric Server
server-port=25565
gamemode=survival
difficulty=normal
max-players=10
motd=\u00a7b\u00a7lFabric 1.21.1 \u00a7r\u00a7eon Railway
level-name=world
online-mode=false
enable-query=true
query.port=25565
view-distance=8
simulation-distance=6
spawn-protection=0
pvp=true
allow-nether=true
enable-command-block=true
max-tick-time=120000
network-compression-threshold=256
rate-limit=0
white-list=false
enforce-secure-profile=false